sudo: required
services:
   - docker

before_install
 - docker build -t shripada/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shripada/multi-docker-test npm test -- --coverage

after_success:
  - docker build -t shripada/multi-client ./client
  - docker build -t shripada/multi-nginx ./nginx
  - docker build -t shripada/multi-server ./server
  - docker build -t shripada/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push shripada/multi-client
  - docker push shripada/multi-nginx
  - docker push shripada/multi-server
  - docker push shripada/multi-worker